---
kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: ${storageclass}
    app: postgre-sql
    role: postgre-sql-data
  name: postgre-sql-pv
  namespace: postgre-sql
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ${storageclass}
  local:
    path: /datadrive/postgre-sql-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "${selectorkey}"
          operator: In
          values:
          - "${selectorvalue}"
  persistentVolumeReclaimPolicy: Retain
