---
kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: ${storageclass}
    app: postgreSQL
    role: postgreSQL-data
  name: postgreSQL-pv
  namespace: postgreSQL
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ${storageclass}
  local:
    path: /datadrive/postgreSQL-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "${selectorkey}"
          operator: In
          values:
          - "${selectorvalue}"
  persistentVolumeReclaimPolicy: Retain
