apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgre-sql
  name: postgre-sql-pvc
  namespace: postgre-sql
spec:
  storageClassName: ${storageclass}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector: 
    matchLabels:
      role: postgre-sql-data
