apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgreSQL
  name: postgreSQL-pvc
  namespace: postgreSQL
spec:
  storageClassName: ${storageclass}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector: 
    matchLabels:
      role: postgreSQL-data
