apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: postgre-sql
  name: postgre-sql
  namespace: postgre-sql
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgre-sql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgre-sql
    spec:
      containers:
      - image: k8s-master:32080/postgres:11.5-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 20
        name: postgre-sql
        ports:
        - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
          initialDelaySeconds: 60
        resources:
          limits:
            cpu: 2
            memory: 2500Mi
          requests:
            cpu: .5
            memory: 2000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgre-sql/data
          name: postgre-sql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgre-sql
        persistentVolumeClaim:
          claimName: postgre-sql-pvc
